// Generated by CoffeeScript 1.8.0
(function() {
  var AuthenticationManager, defer, uuid;

  defer = require('node-promise').defer;

  uuid = require('node-uuid');

  AuthenticationManager = (function() {
    function AuthenticationManager() {}

    AuthenticationManager.constructor = function() {
      return this.anonymousUsers = [];
    };

    AuthenticationManager.decorateMessageWithUser = function(message) {
      var q, user;
      q = defer();
      user = AuthenticationManager.anonymousUsers[message.client] || {
        id: uuid.v4()
      };
      message.user = user;
      q.resolve(user);
      AuthenticationManager.anonymousUsers[message.client] = user;
      return q;
    };

    AuthenticationManager.canUserReadFromThisObject = function(obj, user) {
      return true;
    };

    AuthenticationManager.canUserWriteToThisObject = function(obj, user) {
      return true;
    };

    return AuthenticationManager;

  })();

  module.exports = AuthenticationManager;

}).call(this);

//# sourceMappingURL=AuthenticationManager.js.map
