// Generated by CoffeeScript 1.8.0
(function() {
  var SampleGame, SuperModel, defer, uuid,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SuperModel = require('../lib/SuperModel');

  defer = require('node-promise').defer;

  uuid = require('node-uuid');

  SampleGame = (function(_super) {
    __extends(SampleGame, _super);

    function SampleGame(record) {
      var q;
      this.record = record != null ? record : {};
      this.getRecord = __bind(this.getRecord, this);
      this.toClient = __bind(this.toClient, this);
      q = defer();
      this.id = this.record.id;
      this.name = this.record.name || 'game_' + uuid.v4();
      this.type = 'game';
      if (!this.id) {
        this.id = uuid.v4();
        this.serialize();
      }
      q.resolve(this);
      return q;
    }

    SampleGame.prototype.toClient = function() {
      return this.getRecord();
    };

    SampleGame.prototype.getRecord = function() {
      var record;
      record = {
        id: this.id,
        name: this.name,
        type: this.type
      };
      return record;
    };

    return SampleGame;

  })(SuperModel);

  module.exports = SampleGame;

}).call(this);

//# sourceMappingURL=SampleGame.js.map
