// Generated by CoffeeScript 1.8.0
(function() {
  var SamplePlayer, SuperModel, defer, uuid,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SuperModel = require('../lib/SuperModel');

  defer = require('node-promise').defer;

  uuid = require('node-uuid');

  SamplePlayer = (function(_super) {
    __extends(SamplePlayer, _super);

    function SamplePlayer(record) {
      var q;
      this.record = record != null ? record : {};
      this.getRecord = __bind(this.getRecord, this);
      this.toClient = __bind(this.toClient, this);
      q = defer();
      this.id = this.record.id || uuid.v4();
      this.name = this.record.name || 'player_' + uuid.v4();
      this.type = 'SamplePlayer';
      q.resolve(this);
      return q;
    }

    SamplePlayer.prototype.toClient = function() {
      return this.getRecord();
    };

    SamplePlayer.prototype.getRecord = function() {
      var record;
      record = {
        id: this.id,
        name: this.name,
        type: this.type
      };
      return record;
    };

    return SamplePlayer;

  })(SuperModel);

  module.exports = SamplePlayer;

}).call(this);

//# sourceMappingURL=SamplePlayer.js.map
