// Generated by CoffeeScript 1.8.0
(function() {
  var SamplePlayer, SuperModel, defer, uuid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SuperModel = require('../lib/SuperModel');

  defer = require('node-promise').defer;

  uuid = require('node-uuid');

  SamplePlayer = (function(_super) {
    __extends(SamplePlayer, _super);

    SamplePlayer.type = 'SamplePlayer';

    SamplePlayer.model = [
      {
        name: 'name',
        "public": true,
        value: 'name',
        "default": 'player_' + uuid.v4()
      }
    ];

    function SamplePlayer(record) {
      this.record = record != null ? record : {};
      return SamplePlayer.__super__.constructor.apply(this, arguments);
    }

    return SamplePlayer;

  })(SuperModel);

  module.exports = SamplePlayer;

}).call(this);

//# sourceMappingURL=SamplePlayer.js.map
