// Generated by CoffeeScript 1.10.0
(function() {
  var DB, HttpMethod, ResolveModule, SampleGame, SampleLogic, SamplePlayer, e;

  e = require('../lib/EventManager');

  SampleGame = require('./SampleGame');

  SamplePlayer = require('./SamplePlayer');

  DB = require('../lib/DB');

  HttpMethod = require('../lib/HttpMethod');

  ResolveModule = require('../lib/ResolveModule');

  SampleLogic = (function() {
    SampleLogic.gamecount = 0;

    function SampleLogic(messageRouter) {
      this.messageRouter = messageRouter;
      this.games = [];
      DB.createDatabases(['samplegame', 'sampleplayer']).then((function(_this) {
        return function(results) {
          console.log(' DB init done..');
          _this.messageRouter.objectManager.expose('SampleGame');
          _this.messageRouter.objectManager.expose('SamplePlayer');
          ResolveModule.modulecache['SampleGame'] = SampleGame;
          ResolveModule.modulecache['SamplePlayer'] = SamplePlayer;
          return DB.getOrCreateObjectByRecord({
            id: 17,
            name: 'fooGame',
            type: 'SampleGame',
            createdBy: 'SYSTEM',
            createdAt: Date.now()
          }).then(function(game) {
            console.log('got first game');
            game.serialize();
            return _this.messageRouter.open();
          });
        };
      })(this));
    }

    return SampleLogic;

  })();

  module.exports = SampleLogic;

}).call(this);

//# sourceMappingURL=SampleLogic.js.map
