// Generated by CoffeeScript 1.10.0
(function() {
  var AuthenticationManager, SampleLogic, SpinCycle, app, authMgr, bodyParser, cors, express, logic, messageRouter, port, server, session;

  SpinCycle = require('../lib/MessageRouter');

  AuthenticationManager = require('./AuthenticationManager');

  SampleLogic = require('./SampleLogic');

  express = require("express");

  bodyParser = require("body-parser");

  session = require('express-session');

  cors = require('cors');

  app = express();

  server = require("http").createServer(app);

  app.use(express["static"]("app"));

  app.use(cors);

  app.use(session({
    secret: 'shhhhhhhhh'
  }));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  authMgr = new AuthenticationManager();

  messageRouter = new SpinCycle(authMgr, null, 1000, app);

  new SpinCycle.HttpMethod(messageRouter, app, '/api/');

  new SpinCycle.WsMethod(messageRouter, server);

  logic = new SampleLogic(messageRouter);

  port = process.env.PORT || 6601;

  setTimeout(function() {
    server.listen(port, function() {
      return console.log("Server listening at port %d", port);
    });
  }, 1000);

}).call(this);

//# sourceMappingURL=server.js.map
