// Generated by CoffeeScript 1.10.0
(function() {
  var AuthenticationManager, SampleLogic, SpinCycle, _log, app, authMgr, bodyParser, cors, express, logic, messageRouter, port, serveStatic, server, session;

  SpinCycle = require('../lib/MessageRouter');

  AuthenticationManager = require('./AuthenticationManager');

  SampleLogic = require('./SampleLogic');

  serveStatic = require('serve-static');

  express = require("express");

  bodyParser = require("body-parser");

  session = require('express-session');

  cors = require('cors');

  app = express();

  server = require("http").createServer(app);

  _log = console.log;

  console.log = function(msg) {
    var ts;
    ts = new Date() + "";
    return _log(ts + ' - ' + msg);
  };

  port = process.env.PORT || 6602;

  app.use(cors);

  app.use(session({
    secret: 'shhhhhhhhh'
  }));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  "setTimeout(\n  ()=>\n    app.use(serveStatic(__dirname + '/app'))\n  ,2000\n)";

  app.use(cors());

  server.listen(port, function() {
    return console.log("---*** Server listening at port %d", port);
  });

  authMgr = new AuthenticationManager(app);

  messageRouter = new SpinCycle(authMgr, null, 1000, app, 'mongodb');

  new SpinCycle.HttpMethod(messageRouter, app, '/api/');

  new SpinCycle.WsMethod(messageRouter, server);

  logic = new SampleLogic(messageRouter);

}).call(this);

//# sourceMappingURL=server.js.map
