// Generated by CoffeeScript 1.9.1
(function() {
  var ClientEndpoints;

  ClientEndpoints = (function() {
    function ClientEndpoints() {}

    ClientEndpoints.endpoints = [];

    ClientEndpoints.ondisconnectcbs = [];

    ClientEndpoints.onconnectcbs = [];

    ClientEndpoints.registerEndpoint = function(address, sendFunc) {
      console.log('registerEndpoint called for address ' + address);
      this.endpoints[address] = sendFunc;
      return this.onconnectcbs.forEach((function(_this) {
        return function(cb) {
          return cb(address);
        };
      })(this));
    };

    ClientEndpoints.removeEndpoint = function(address) {
      console.log('deleting endpoint ' + address);
      delete this.endpoints[address];
      return this.ondisconnectcbs.forEach((function(_this) {
        return function(cb) {
          return cb(address);
        };
      })(this));
    };

    ClientEndpoints.sendToEndpoint = function(address, msg) {
      var func;
      func = this.endpoints[address];
      if (func) {
        return func(msg);
      } else {
        return console.log('** no endpoint found for address ' + address);
      }
    };

    ClientEndpoints.onDisconnect = function(cb) {
      return ClientEndpoints.ondisconnectcbs.push(cb);
    };

    ClientEndpoints.onConnect = function(cb) {
      return ClientEndpoints.onconnectcbs.push(cb);
    };

    return ClientEndpoints;

  })();

  module.exports = ClientEndpoints;

}).call(this);

//# sourceMappingURL=ClientEndpoints.js.map
