// Generated by CoffeeScript 1.9.1
(function() {
  var Roach;

  Roach = require('roachjs');

  Class(cockroach({
    constructor: function() {
      return this.client = new Roach({
        uri: 'http://127.0.0.1:8080'
      });
    }
  }));

  module.exports = cockroach;

}).call(this);

//# sourceMappingURL=cockroach.js.map
