// Generated by CoffeeScript 1.9.1
(function() {
  var Error;

  Error = (function() {
    function Error() {}

    Error.error = function() {
      console.log('*************************************************************************************************');
      console.log(' ERROR:');
      console.dir(arguments);
      return console.log('*************************************************************************************************');
    };

    return Error;

  })();

  module.exports = Error;

}).call(this);

//# sourceMappingURL=Error.js.map
