// Generated by CoffeeScript 1.9.1
(function() {
  var EventManager,
    slice = [].slice;

  EventManager = (function() {
    function EventManager() {}

    EventManager.general = {
      SUCCESS: 'SUCCESS',
      FAILURE: 'FAILURE',
      NOT_ALLOWED: 'NOT_ALLOWED',
      NOOP: 'NOOP'
    };

    EventManager.gamemanager = {
      REGISTER_UPDATES: 'REGISTER_UPDATES',
      DEREGISTER_UPDATES: 'DEREISTER_UODATES',
      OBJECT_UPDATE: 'OBJECT_UPDATE',
      UPDATE_REGISTER_FAIL: 'UPDATE_REGISTER_FAIL',
      UPDATE_OBJECT_SUCCESS: 'UPDATE_OBJECT_SUCCESS',
      UPDATE_OBJECT_FAIL: 'UPDATE_OBJECT_FAIL',
      NO_SUCH_OBJECT: 'NO_SUCH_OBJECT'
    };

    EventManager.event = function() {
      var e, i, key, ref, rv;
      e = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      rv = [];
      for (key = i = 0, ref = e.length - 1; i <= ref; key = i += 2) {
        rv.push({
          e: e[key],
          o: e[key + 1] || {}
        });
      }
      return rv;
    };

    return EventManager;

  })();

  module.exports = EventManager;

}).call(this);

//# sourceMappingURL=EventManager.js.map
