// Generated by CoffeeScript 1.10.0
(function() {
  var GooglePersistence, debug, defer, gcloud,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  gcloud = require('gcloud');

  defer = require('node-promise').defer;

  debug = process.env["DEBUG"];

  GooglePersistence = (function() {
    function GooglePersistence(dburl, DB) {
      this.dburl = dburl;
      this.DB = DB;
      this.remove = bind(this.remove, this);
      this.set = bind(this.set, this);
      this.search = bind(this.search, this);
      this.findQuery = bind(this.findQuery, this);
      this.findMany = bind(this.findMany, this);
      this.find = bind(this.find, this);
      this.get = bind(this.get, this);
      this.count = bind(this.count, this);
      this.all = bind(this.all, this);
      this.getDbFor = bind(this.getDbFor, this);
      this.connect = bind(this.connect, this);
      this.connection = void 0;
      this.dbs = [];
    }

    GooglePersistence.prototype.connect = function() {
      var q;
      console.log('Google connect called...');
      q = defer();
      q.resolve(this);
      return q;
    };

    GooglePersistence.prototype.getDbFor = function(_type) {
      var dataset, db, q, type;
      q = defer();
      type = _type.toLowerCase();
      db = this.dbs[type];
      if (db) {
        q.resolve(db);
      } else {
        dataset = gcloud.datastore({
          projectId: process.env.GCLOUD_PROJECT,
          namespace: 'spincycle'
        });
        this.dbs[type] = dataset;
        q.resolve(dataset);
      }
      return q;
    };

    GooglePersistence.prototype.all = function(_type, cb) {
      var type;
      type = _type.toLowerCase();
      if (debug) {
        console.log('Google.all called for ' + type);
      }
      return this.getDbFor(type).then((function(_this) {
        return function(db) {
          var query;
          query = db.createQuery(type).limit(10000);
          return db.runQuery(query, function(err, entities) {
            var result;
            if (err) {
              if (debug) {
                console.log('Google.all ERROR: ' + err);
              }
              if (debug) {
                console.dir(err);
              }
              return cb();
            } else {
              if (debug) {
                console.log('Google.all returns ' + entities.length + ' entities');
              }
              result = entities.map(function(el) {
                return el.data;
              });
              return cb(result);
            }
          });
        };
      })(this));
    };

    GooglePersistence.prototype.count = function(_type) {
      var q, type;
      if (debug) {
        console.log('Google.count called');
      }
      type = _type.toLowerCase();
      q = defer();
      this.getDbFor(type).then((function(_this) {
        return function(db) {
          var count, query;
          query = db.createQuery('__Stat_spincycle_' + type + '__');
          count = query.getproeprties('count');
          console.log('Google.count return ' + count);
          q.resolve(count);
          return "db.runQuery query, (err, entities) ->\n  if err\n    if debug then console.log 'Google.all ERROR: '+err\n    if debug then console.dir err\n    cb()\n  else\n    if debug then console.log 'Google.all returns '+entities.length+' entities'\n    if debug then console.dir entities\n    cb(entities)";
        };
      })(this));
      return q;
    };

    GooglePersistence.prototype.get = function(_type, id, cb) {
      var type;
      type = _type.toLowerCase();
      return this.getDbFor(type).then((function(_this) {
        return function(db) {
          var key;
          key = db.key([type, id]);
          return db.get({
            key: key
          }, function(err, entity) {
            if (err) {
              if (debug) {
                console.log('Google.get ERROR: ' + err);
              }
              if (debug) {
                console.dir(err);
              }
              return cb();
            } else {
              if (debug) {
                console.log('Google.get returns entity for ' + type + ' id = ' + id);
              }
              if (debug) {
                console.dir(entity);
              }
              return cb(entity);
            }
          });
        };
      })(this));
    };

    GooglePersistence.prototype.find = function(_type, property, _value) {
      return this.findMany(_type, property, _value);
    };

    GooglePersistence.prototype.findMany = function(_type, property, _value) {
      var q, type, value;
      q = defer();
      value = _value || "";
      type = _type.toLowerCase();
      if (debug) {
        console.log('Google.findMany called for ' + type + ' filtering on ' + property + ' = ' + value);
      }
      this.getDbFor(type).then((function(_this) {
        return function(db) {
          var query;
          query = db.createQuery(type).limit(10000).filter(property, '=', value);
          return db.runQuery(query, function(err, entities) {
            var result;
            if (err) {
              if (debug) {
                console.log('Google.findMany ERROR: ' + err);
              }
              if (debug) {
                console.dir(err);
              }
              return q.resolve();
            } else {
              if (debug) {
                console.log('Google.all returns ' + entities.length + ' entities');
              }
              result = entities.map(function(el) {
                return el.data;
              });
              return q.resolve(result);
            }
          });
        };
      })(this));
      return q;
    };

    GooglePersistence.prototype.findQuery = function(_type, query) {
      return this.findMany(_type, query.property, query.value);
    };

    GooglePersistence.prototype.search = function(_type, property, _value) {
      return this.findMany(_type, property, _value);
    };

    GooglePersistence.prototype.set = function(_type, obj, cb) {
      var type;
      type = _type.toLowerCase();
      if (debug) {
        console.log('-- Google.set called for ' + type + ' - ' + JSON.stringify(obj));
      }
      return this.getDbFor(type).then((function(_this) {
        return function(db) {
          var key;
          if (!obj.id) {
            key = db.key(type);
            obj.id = key.path[1];
          } else {
            key = db.key(type, obj.id);
          }
          return db.upsert({
            key: key,
            data: obj
          }, function(err) {
            if (debug) {
              console.log('-- Google.set done for ' + type + ' ' + obj.id + ' !');
            }
            if (err) {
              if (debug) {
                console.log('Google.set ERROR: ' + err);
              }
              if (debug) {
                console.dir(err);
              }
              return cb();
            } else {
              return cb(obj);
            }
          });
        };
      })(this));
    };

    GooglePersistence.prototype.remove = function(_type, obj, cb) {
      var id, type;
      if (debug) {
        console.log('Google.remove called');
      }
      type = _type.toLowerCase();
      id = obj.id;
      return this.getDbFor(type).then((function(_this) {
        return function(db) {
          var key;
          key = db.key(type, obj.id);
          return db["delete"](key, function(err, apiResponse) {
            if (err) {
              if (debug) {
                console.log('Google.remove ERROR: ' + apiResponse);
              }
              if (debug) {
                console.dir(apiResponse);
              }
              return cb(false);
            } else {
              return cb(true);
            }
          });
        };
      })(this));
    };

    return GooglePersistence;

  })();

  module.exports = GooglePersistence;

}).call(this);

//# sourceMappingURL=GooglePersistence.js.map
