// Generated by CoffeeScript 1.8.0
(function() {
  var HttpMethod, url, uuid;

  uuid = require('node-uuid');

  url = require('url');

  HttpMethod = (function() {
    HttpMethod.httproutes = [];

    function HttpMethod(messageRouter, app, basePath) {
      app.use(basePath + ':target', function(req, res) {
        var ip, message, p, part, port, target, url_parts;
        ip = req.connection.remoteAddress;
        port = req.connection.remotePort;
        target = HtpMethod.httproutes[req.params.target];
        if (target) {
          url_parts = url.parse(req.url, true);
          message = {
            client: ip + ':' + port,
            target: req.params.target,
            messageId: url_parts.messageId || uuid.v4()
          };
          for (p in url_parts) {
            part = url_parts[p];
            message[p] = part;
          }
          message.replyFunc = function(reply) {
            res.json(reply);
            return console.log('express calling target');
          };
          return target(message);
        }
      });
      messageRouter.addMethod('express', function(targetName, targetFunc) {
        return HttpMethod.httproutes[targetName] = targetFunc;
      });
    }

    return HttpMethod;

  })();

  module.exports = HttpMethod;

}).call(this);

//# sourceMappingURL=HttpMethod.js.map
