// Generated by CoffeeScript 1.8.0
(function() {
  var ClientEndpoints, DB, EventManager, HttpMethod, MessageRouter, ObjectManager, SuperModel, WsMethod, error,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ObjectManager = require('./ObjectManager');

  error = require('./Error').error;

  HttpMethod = require('./HttpMethod');

  WsMethod = require('./WsMethod');

  DB = require('./DB');

  EventManager = require('./EventManager');

  SuperModel = require('./SuperModel');

  ClientEndpoints = require('./ClientEndpoints');

  MessageRouter = (function() {
    MessageRouter.HttpMethod = HttpMethod;

    MessageRouter.WsMethod = WsMethod;

    MessageRouter.DB = DB;

    MessageRouter.EventManager = EventManager;

    MessageRouter.SuperModel = SuperModel;

    MessageRouter.DB = DB;

    MessageRouter.ObjectManager = ObjectManager;

    MessageRouter.ClientEndpoints = ClientEndpoints;

    function MessageRouter(authMgr) {
      var objectManager;
      this.authMgr = authMgr;
      this.routeMessage = __bind(this.routeMessage, this);
      this.removeTarget = __bind(this.removeTarget, this);
      this.addTarget = __bind(this.addTarget, this);
      this.addMethod = __bind(this.addMethod, this);
      this.setup = __bind(this.setup, this);
      console.log('messageRouter constructor');
      console.dir(this.authMgr);
      this.targets = [];
      this.args = [];
      this.methods = [];
      objectManager = new ObjectManager(this);
      objectManager.setup();
      this.setup();
    }

    MessageRouter.prototype.setup = function() {
      return this.addTarget('listcommands', '<noargs>', (function(_this) {
        return function(msg) {
          var name, rv, target, _ref;
          console.log('listCommands called');
          rv = {
            listcommands: '<noarg>'
          };
          _ref = _this.targets;
          for (name in _ref) {
            target = _ref[name];
            console.log('adding target ' + name);
            rv[name] = _this.args[name];
          }
          return msg.replyFunc(rv);
        };
      })(this));
    };

    MessageRouter.prototype.addMethod = function(methodName, registrationFunc) {
      var targetName, _results;
      this.methods[methodName] = registrationFunc;
      _results = [];
      for (targetName in this.targets) {
        _results.push(registrationFunc(targetName, this.routeMessage));
      }
      return _results;
    };

    MessageRouter.prototype.addTarget = function(targetName, args, targetFunc) {
      var method, registrationFunc, _ref, _results;
      console.log('adding route target for "' + targetName + '"');
      this.targets[targetName] = targetFunc;
      this.args[targetName] = args;
      _ref = this.methods;
      _results = [];
      for (method in _ref) {
        registrationFunc = _ref[method];
        _results.push(registrationFunc(targetName, this.routeMessage));
      }
      return _results;
    };

    MessageRouter.prototype.removeTarget = function(targetName) {
      return this.targets[targetName] = null;
    };

    MessageRouter.prototype.routeMessage = function(message) {
      var fn;
      fn = this.targets[message.target];
      console.log('routeMessage called for "' + message.target + '"');
      if (fn) {
        return this.authMgr.decorateMessageWithUser(message).then(function(m) {
          if (!m.user) {
            console.log('** SpinCycle did not get message decorated with user property from AuthenticationManager **');
            exit(-1);
          }
          return fn(m);
        });
      } else {
        return console.log('--- could not find registered target for message! ---');
      }
    };

    return MessageRouter;

  })();

  module.exports = MessageRouter;

}).call(this);

//# sourceMappingURL=MessageRouter.js.map
