// Generated by CoffeeScript 1.9.1
(function() {
  var Db, MongoClient, MongoPersistence, Server, debug, defer,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Db = require('mongodb').Db;

  Server = require('mongodb').Server;

  MongoClient = require('mongodb').MongoClient;

  defer = require('node-promise').defer;

  debug = process.env["DEBUG"];

  MongoPersistence = (function() {
    var madr, mport;

    if (process.env['MONGODB_PORT_27017_TCP_PORT']) {
      madr = 'mongodb';
    } else {
      madr = '127.0.0.1';
    }

    mport = process.env['MONGODB_PORT_27017_TCP_PORT'] || '27017';

    function MongoPersistence() {
      this.remove = bind(this.remove, this);
      this.set = bind(this.set, this);
      this.search = bind(this.search, this);
      this.find = bind(this.find, this);
      this.byProviderId = bind(this.byProviderId, this);
      this.get = bind(this.get, this);
      this.all = bind(this.all, this);
      this.getDbFor = bind(this.getDbFor, this);
      this.foo = bind(this.foo, this);
      this.getConnection = bind(this.getConnection, this);
      this.connect = bind(this.connect, this);
      this.dbs = [];
    }

    MongoPersistence.prototype.connect = function() {
      return console.log('Mongo connect called');
    };

    MongoPersistence.prototype.getConnection = function() {
      var q;
      q = defer();
      if (this.db) {
        q.resolve(this.db);
      } else {
        this.foo(q);
      }
      return q;
    };

    MongoPersistence.prototype.foo = function(q) {
      var cstring;
      cstring = 'mongodb://' + madr + ':' + mport + '/spincycle';
      return MongoClient.connect(cstring, (function(_this) {
        return function(err, db) {
          if (err) {
            console.log('MONGO Error connecting to "' + cstring + '" ' + err);
            console.dir(err);
            console.log('retrying.....');
            return setTimeout(function() {
              return _this.foo(q);
            }, 2000);
          } else {
            console.log("---- We are connected ----");
            _this.db = db;
            return q.resolve(db);
          }
        };
      })(this));
    };

    MongoPersistence.prototype.getDbFor = function(_type) {
      var db, q, type;
      q = defer();
      type = _type.toLowerCase();
      db = this.dbs[type];
      if (!db) {
        this.getConnection().then((function(_this) {
          return function(connection) {
            return connection.collection(type, function(err, collection) {
              if (err) {
                console.log('MONGO Error getting collection: ' + err);
                console.dir(err);
                return q.resolve(null);
              } else {
                _this.dbs[type] = collection;
                return q.resolve(collection);
              }
            });
          };
        })(this));
      } else {
        q.resolve(db);
      }
      return q;
    };

    MongoPersistence.prototype.all = function(_type, cb) {
      var type;
      type = _type.toLowerCase();
      return this.getDbFor(type).then((function(_this) {
        return function(collection) {
          return collection.find().toArray(function(err, items) {
            if (err) {
              console.log('MONGO Error getting all: ' + err);
              console.dir(err);
              return cb(null);
            } else {
              return cb(items);
            }
          });
        };
      })(this));
    };

    MongoPersistence.prototype.get = function(_type, id, cb) {
      var type;
      type = _type.toLowerCase();
      if (typeof id === 'object') {
        console.log('Mongo.get got an object as id instead of string !!!!! ');
        cb(null);
      }
      return this.getDbFor(type).then((function(_this) {
        return function(collection) {
          return collection.findOne({
            id: id
          }, function(err, item) {
            if (err) {
              console.log('MONGO get Error: ' + err);
              console.dir(err);
              return cb(null);
            } else {
              return cb(item);
            }
          });
        };
      })(this));
    };

    MongoPersistence.prototype.byProviderId = function(_type, pid) {
      var q, type;
      console.log('byProviderId called for pid ' + pid + ' and type ' + _type);
      q = defer();
      type = _type.toLowerCase();
      this.getDbFor(type).then((function(_this) {
        return function(collection) {
          return collection.findOne({
            providerId: pid
          }, function(err, item) {
            if (err) {
              console.log('MONGO byProviderId Error: ' + err);
              console.dir(err);
              return q.resolve(null);
            } else {
              return q.resolve(item);
            }
          });
        };
      })(this));
      return q;
    };

    MongoPersistence.prototype.find = function(_type, property, value) {
      var q, type;
      console.log('Mongo find called for type ' + _type + ' property ' + property + ' and value ' + value);
      q = defer();
      type = _type.toLowerCase();
      this.getDbFor(type).then((function(_this) {
        return function(collection) {
          var query;
          query = {};
          query[property] = value;
          return collection.findOne(query, function(err, item) {
            if (err) {
              console.log('MONGO find Error: ' + err);
              console.dir(err);
              return q.resolve(null);
            } else {
              return q.resolve(item);
            }
          });
        };
      })(this));
      return q;
    };

    MongoPersistence.prototype.search = function(_type, property, value) {
      var q, type;
      console.log('Mongo search called for type ' + _type + ' property ' + property + ' and value ' + value);
      q = defer();
      type = _type.toLowerCase();
      this.getDbFor(type).then((function(_this) {
        return function(collection) {
          var query;
          query = {};
          query[property] = {
            $regex: '^' + value
          };
          if (debug) {
            console.log('mongo find query is');
          }
          if (debug) {
            console.dir(query);
          }
          return collection.find(query, function(err, items) {
            if (err) {
              console.log('MONGO search Error: ' + err);
              console.dir(err);
              return q.resolve(null);
            } else {
              return items.toArray(function(err2, docs) {
                if (err2) {
                  console.log('MONGO search toArray Error: ' + err2);
                  return console.dir(err2);
                } else {
                  return q.resolve(docs);
                }
              });
            }
          });
        };
      })(this));
      return q;
    };

    MongoPersistence.prototype.set = function(_type, obj, cb) {
      var type;
      type = _type.toLowerCase();
      return this.getDbFor(type).then((function(_this) {
        return function(collection) {
          if (typeof obj.id === 'object') {
            console.dir(obj);
          }
          return collection.update({
            id: obj.id
          }, obj, {
            upsert: true
          }, function(err, result, upserted) {
            if (err) {
              console.log('MONGO set Error: ' + err);
              console.dir(err);
              return cb(null);
            } else {
              return cb(result);
            }
          });
        };
      })(this));
    };

    MongoPersistence.prototype.remove = function(_type, obj, cb) {
      var type;
      type = _type.toLowerCase();
      return this.getDbFor(type).then((function(_this) {
        return function(collection) {
          return collection.remove({
            id: obj.id
          }, {
            w: 1
          }, function(err, numberOfRemovedDocs) {
            if (err) {
              console.log('MONGO remove Error: ' + err);
              console.dir(err);
              return cb(null);
            } else {
              return cb(obj);
            }
          });
        };
      })(this));
    };

    return MongoPersistence;

  })();

  module.exports = MongoPersistence;

}).call(this);

//# sourceMappingURL=MongoPersistence.js.map
