// Generated by CoffeeScript 1.8.0
(function() {
  var DB, OStore, defer, error, uuid;

  defer = require('node-promise').defer;

  DB = require('./DB');

  uuid = require('node-uuid');

  error = require('./../Error').error;

  OStore = (function() {
    function OStore() {}

    OStore.objects = [];

    OStore.listeners = [];

    OStore.storeObj = function(obj) {
      var lid, list, listener, _results;
      OStore.objects[obj.id] = obj;
      list = OStore.listeners[obj.id] || [];
      if (obj.type === 'entity') {
        console.log('oMgr::storeObj there are ' + list.length + ' listener for ' + obj.type + ' ' + obj.id);
      }
      _results = [];
      for (lid in list) {
        listener = list[lid];
        console.log('+ DB.set sending update for id ' + obj.id);
        _results.push(listener(diff));
      }
      return _results;
    };

    OStore.getObj = function(id, type) {
      var q, resolve;
      q = defer();
      resolve = function(obj) {
        OStore.storeObj(obj);
        return q.resolve(obj);
      };
      q.resolve(OStore.objects[id]);

      /*rv = OStore.objects[id]
      if rv
        q.resolve(rv)
      else
        DB.get(id, type).then (record) =>
          switch type
            when 'game'   then new Game(record).then((gobj)     => resolve(gobj))
            when 'zone'   then new Zone(record).then((zobj)     => resolve(zobj))
            when 'entity' then new Entity(record).then((eobj)   => resolve(eobj))
            when 'player' then new Player(record).then((pobj)   => resolve(pobj))
            when 'thing'  then new Thing(record).then((tobj)    => resolve(tobj))
            when 'tile'   then new Tile(record).then((tobj)     => resolve(tobj))
       */
      return q;
    };

    OStore.updateObj = function(kv) {
      var lid, list, listener, obj, p, pp, whitelist;
      obj = OStore.objects[kv.id];
      whitelist = obj.getRecord();
      for (p in whitelist) {
        for (pp in kv) {
          if (pp === p) {
            console.log('  object update property ' + p + ' was in whitelist');
            obj[pp] = kv[pp];
          }
        }
      }
      list = OStore.listeners[obj.id] || [];
      console.log("-- oMgr::storeObj there are " + list.length + " listener for " + obj.type + " " + obj.id);
      for (lid in list) {
        listener = list[lid];
        console.log("--  oMgr.set sending update for id " + obj.id);
        listener(obj);
      }
    };

    OStore.addListenerFor = function(id, type, cb) {
      var list, listenerId;
      list = OStore.listeners[id] || [];
      listenerId = uuid.v4();
      list[listenerId] = cb;
      OStore.listeners[id] = list;
      console.log('--  oMgr adding listener for id ' + id);
      console.log('-- sending first update of object as baseline..');
      OStore.getObj(id, type).then(function(result) {
        return cb(result);
      }, error);
      return listenerId;
    };

    OStore.removeListenerFor = function(id, listenerId) {
      var cb, i, list, tmp;
      list = OStore.listeners[id] || [];
      delete list[listenerId];
      tmp = [];
      for (i in list) {
        cb = list[i];
        if (cb) {
          tmp[i] = cb;
        }
      }
      return OStore.listeners[id] = tmp;
    };

    return OStore;

  })();

  module.exports = OStore;

}).call(this);

//# sourceMappingURL=OStore.js.map
