// Generated by CoffeeScript 1.8.0
(function() {
  var DB, OStore, defer, error, uuid;

  defer = require('node-promise').defer;

  DB = require('./DB');

  uuid = require('node-uuid');

  error = require('./Error').error;

  OStore = (function() {
    function OStore() {}

    OStore.objects = [];

    OStore.listeners = [];

    OStore.storeObj = function(obj) {
      var lid, list, listener, _results;
      OStore.objects[obj.id] = obj;
      list = OStore.listeners[obj.id] || [];
      _results = [];
      for (lid in list) {
        listener = list[lid];
        _results.push(listener(diff));
      }
      return _results;
    };

    OStore.getObj = function(id, type) {
      var q;
      q = defer();
      q.resolve(OStore.objects[id]);
      return q;
    };

    OStore.updateObj = function(kv) {
      var lid, list, listener, obj, p, pp, whitelist;
      obj = OStore.objects[kv.id];
      whitelist = obj.getRecord();
      for (p in whitelist) {
        for (pp in kv) {
          if (pp === p) {
            obj[pp] = kv[pp];
          }
        }
      }
      list = OStore.listeners[obj.id] || [];
      for (lid in list) {
        listener = list[lid];
        listener(obj);
      }
    };

    OStore.addListenerFor = function(id, type, cb) {
      var list, listenerId;
      list = OStore.listeners[id] || [];
      listenerId = uuid.v4();
      list[listenerId] = cb;
      OStore.listeners[id] = list;
      OStore.getObj(id, type).then(function(result) {
        return cb(result);
      }, error);
      return listenerId;
    };

    OStore.removeListenerFor = function(id, listenerId) {
      var cb, i, list, tmp;
      list = OStore.listeners[id] || [];
      delete list[listenerId];
      tmp = [];
      for (i in list) {
        cb = list[i];
        if (cb) {
          tmp[i] = cb;
        }
      }
      return OStore.listeners[id] = tmp;
    };

    return OStore;

  })();

  module.exports = OStore;

}).call(this);

//# sourceMappingURL=OStore.js.map
