// Generated by CoffeeScript 1.9.1
(function() {
  var ClientEndpoints, RedisMethod, redis, uuid,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  uuid = require('node-uuid');

  redis = require('redis');

  ClientEndpoints = require('./ClientEndpoints');

  RedisMethod = (function() {
    function RedisMethod(messageRouter, app, basePath) {
      this.registrationFunc = bind(this.registrationFunc, this);
      this.onChannelMessage = bind(this.onChannelMessage, this);
      this.redisroutes = [];
      this.listenclient = redis.createClient();
      this.sendclient = redis.createClient();
      this.listenclient.subscribe('spinchannel');
      this.listenclient.on('message', this.onChannelMessage);
      messageRouter.addMethod('redis', this);
    }

    RedisMethod.prototype.onChannelMessage = function(channel, message) {
      var clientChannel, msg, target;
      console.log('redismethod got channel ' + channel + ' message ' + message);
      console.dir(channel);
      console.log('-------------------------------------------------------------------');
      msg = JSON.parse(message);
      console.dir(msg);
      clientChannel = msg.channelID;
      if (clientChannel) {
        ClientEndpoints.registerEndpoint(msg.channelID, function(msg) {
          return this.sendclient.publish(clientChannel, JSON.stringify(msg));
        });
      }
      target = this.redisroutes[msg.target];
      if (target) {
        msg.client = data.messageId;
        msg.messageId = data.messageId || uuid.v4();
        return msg.replyFunc = (function(_this) {
          return function(replydata) {
            replydata.messageId = data.messageId;
            return _this.sendclient.publish(clientChannel, JSON.stringify(replydata));
          };
        })(this);
      } else {
        console.log('RedisMethod: could not find target "' + msg.target + '" sending failure back to channel "' + clientChannel + '"');
        return this.sendclient.publish(clientChannel, JSON.stringify({
          messageId: msg.messageId,
          status: 'FAILURE',
          info: 'could not find target "' + msg.target + '"',
          payload: null
        }));
      }
    };

    RedisMethod.prototype.registrationFunc = function(targetName, targetFunc) {
      return this.redisroutes[targetName] = targetFunc;
    };

    return RedisMethod;

  })();

  module.exports = RedisMethod;

}).call(this);

//# sourceMappingURL=RedisMethod.js.map
