// Generated by CoffeeScript 1.9.1
(function() {
  var RedisMethod, redis, uuid,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  uuid = require('node-uuid');

  redis = require('redis');

  RedisMethod = (function() {
    function RedisMethod(messageRouter, app, basePath) {
      this.expose = bind(this.expose, this);
      this.redisroutes = [];
      this.listenclient = redis.createClient();
      this.sendclient = redis.createClient();
      this.listenclient.subscribe('spinchannel');
      this.listenclient.on('message', this.onChannelMessage);
      messageRouter.addMethod('redis', this);
    }

    RedisMethod.prototype.onChannelMessage = function(channel, message) {
      var clientChannel, msg, target;
      console.log('redismethod got channel ' + channel + ' message ' + message);
      console.dir(channel);
      console.log('-------------------------------------------------------------------');
      msg = JSON.parse(message);
      console.dir(msg);
      clientChannel = msg.channelId;
      target = this.redisroutes[msg.target];
      if (target) {
        msg.client = ip + ':' + port;
        msg.messageId = data.messageId || uuid.v4();
        return msg.replyFunc = function(replydata) {
          replydata.messageId = data.messageId;
          return this.sendclient.publisht(clientChannel, replydata);
        };
      }
    };

    RedisMethod.prototype.registrationFunc = function(targetName, targetFunc) {
      return this.redisroutes[targetName] = targetFunc;
    };

    RedisMethod.prototype.expose = function(type) {
      return console.log('RedisMethod::Expose called for type ' + type + ' (unimplemented)');
    };

    return RedisMethod;

  })();

  module.exports = RedisMethod;

}).call(this);

//# sourceMappingURL=RedisMethod.js.map
