// Generated by CoffeeScript 1.8.0
(function() {
  var ResolveModule,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ResolveModule = (function() {
    function ResolveModule(basepath) {
      this.basepath = basepath;
      this.resolve = __bind(this.resolve, this);
      console.log("+++ new ResolveModule created ++");
      process.on('resolvemodule', (function(_this) {
        return function(name, cb) {
          return _this.resolve(name, cb);
        };
      })(this));
    }

    ResolveModule.prototype.resolve = function(name, cb) {
      var finder, rv;
      rv = null;
      finder = require('findit')(this.basepath);
      finder.on('directory', function(dir) {});
      finder.on('file', function(file) {
        if (file.indexOf(name + '.js') > -1) {
          if (!file.indexOf('.map' && !file.indexOf('.coffee'))) {
            rv = file;
            finder.stop();
            return cb(rv);
          }
        }
      });
      return finder.on('end', function() {});
    };

    return ResolveModule;

  })();

  module.exports = ResolveModule;

}).call(this);

//# sourceMappingURL=ResolveModule.js.map
