// Generated by CoffeeScript 1.8.0
(function() {
  var ResolveModule, debug, defer, dirname,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  defer = require('node-promise').defer;

  debug = process.env["DEBUG"];

  console.log('resolvemodule dirname is ' + __dirname);

  console.log(__dirname);

  dirname = __dirname.substring(0, __dirname.indexOf('/node_modules'));

  if (__dirname.indexOf('node_modules') === -1) {
    dirname = '../..';
  }

  console.log('starting module resolving from path ' + dirname);

  ResolveModule = (function() {
    ResolveModule.modulecache = [];

    ResolveModule.modulepathcache = [];

    function ResolveModule() {
      this.createObjectFrom = __bind(this.createObjectFrom, this);
      this.resolve = __bind(this.resolve, this);
      console.log("+++ new ResolveModule created ++");
      process.on('resolvemodule', (function(_this) {
        return function(name, cb) {
          return _this.resolve(name, cb);
        };
      })(this));
    }

    ResolveModule.prototype.resolve = function(name, cb) {
      var finder, rv;
      rv = ResolveModule.modulepathcache[name];
      if (rv) {
        return cb(rv);
      } else {
        if (debug) {
          console.log('.. looking up module ' + name);
        }
        finder = require('findit')(dirname);
        finder.on('file', function(origfile) {
          var file;
          file = "" + origfile;
          if (file.indexOf('/') > -1) {
            file = file.substring(file.lastIndexOf('/') + 1, file.length);
          }
          if (file.indexOf('.') > -1) {
            file = file.substring(0, file.indexOf('.'));
          }
          if (file === name && origfile.indexOf('.js') > -1 && origfile.indexOf('.map') === -1) {
            rv = origfile;
            ResolveModule.modulepathcache[name] = rv;
            finder.stop();
            return cb(rv);
          }
        });
        return finder.on('end', function() {});
      }
    };

    ResolveModule.prototype.createObjectFrom = function(record) {
      var q;
      q = defer();
      if (!record || (record[0] && (record[0] === null) || record[0] === 'null')) {
        q.resolve(null);
      } else {
        if (!record[0]) {
          record = [record];
        }
        if (!record[0].id) {
          q.resolve(null);
        } else {
          this.resolve(record[0].type, function(filename) {
            var module, o;
            module = ResolveModule.modulecache[record[0].type] || require(filename.replace('.js', ''));
            ResolveModule.modulecache[record[0].type] = module;
            o = Object.create(module.prototype);
            o._rev = record._rev;
            o.constructor(record[0]);
            return q.resolve(o);
          });
        }
      }
      return q;
    };

    return ResolveModule;

  })();

  module.exports = ResolveModule;

}).call(this);

//# sourceMappingURL=ResolveModule.js.map
