// Generated by CoffeeScript 1.9.3
(function() {
  var SpinApp, SuperModel, all, defer,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  SuperModel = require('./SuperModel');

  defer = require('node-promise').defer;

  all = require('node-promise').allOrNone;

  SpinApp = (function(superClass) {
    extend(SpinApp, superClass);

    SpinApp.type = 'SpinApp';

    SpinApp.model = [
      {
        name: 'name',
        "public": true,
        value: 'name',
        "default": 'Spin App'
      }, {
        name: 'comment',
        "public": true,
        value: 'comment',
        "default": ' '
      }, {
        name: 'endpoint',
        "public": true,
        value: 'endpoint',
        "default": '/spinapp'
      }, {
        name: 'targetModule',
        "public": true,
        value: 'targetModule',
        type: 'SpinModule',
        "default": ' '
      }, {
        name: 'targetInput',
        "public": true,
        value: 'targetInput',
        "default": ' '
      }, {
        name: 'version',
        "public": true,
        value: 'version',
        "default": '0.0'
      }
    ];

    function SpinApp(record) {
      this.record = record;
      this.postCreate = bind(this.postCreate, this);
      return SpinApp.__super__.constructor.apply(this, arguments);
    }

    SpinApp.prototype.postCreate = function(q) {
      return q.resolve(this);
    };

    return SpinApp;

  })(SuperModel);

  module.exports = SpinApp;

}).call(this);

//# sourceMappingURL=SpinApp.js.map
