// Generated by CoffeeScript 1.9.3
(function() {
  var SpinModule, SuperModel, all, defer,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  SuperModel = require('./SuperModel');

  defer = require('node-promise').defer;

  all = require('node-promise').allOrNone;

  SpinModule = (function(superClass) {
    extend(SpinModule, superClass);

    SpinModule.type = 'SpinModule';

    SpinModule.model = [
      {
        name: 'name',
        "public": true,
        value: 'name',
        "default": 'Spin Module'
      }, {
        name: 'inputs',
        "public": true,
        value: 'inputs',
        "default": []
      }, {
        name: 'outputs',
        "public": true,
        value: 'outputs',
        "default": []
      }, {
        name: 'moduleConnections',
        "public": true,
        value: 'moduleConnections',
        "default": []
      }, {
        name: 'state',
        "public": true,
        value: 'state',
        "default": {}
      }, {
        name: 'functions',
        "public": true,
        ids: 'functions',
        array: true,
        type: 'SpinFunction',
        "default": []
      }, {
        name: 'modules',
        "public": true,
        ids: 'modules',
        array: true,
        type: 'SpinModule',
        "default": []
      }, {
        name: 'tests',
        "public": true,
        value: 'tests',
        "default": []
      }, {
        name: 'version',
        "public": true,
        value: 'version',
        "default": '0.0'
      }
    ];

    function SpinModule(record) {
      this.record = record;
      this.postCreate = bind(this.postCreate, this);
      return SpinModule.__super__.constructor.apply(this, arguments);
    }

    SpinModule.prototype.postCreate = function(q) {
      return q.resolve(this);
    };

    return SpinModule;

  })(SuperModel);

  module.exports = SpinModule;

}).call(this);

//# sourceMappingURL=SpinModule.js.map
