// Generated by CoffeeScript 1.8.0
(function() {
  var SpinFunction, SuperModel, all, defer,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SuperModel = require('./SuperModel');

  defer = require('node-promise').defer;

  all = require('node-promise').allOrNone;

  SpinFunction = (function(_super) {
    __extends(SpinFunction, _super);

    SpinFunction.type = 'SpinFunction';

    SpinFunction.model = [
      {
        name: 'name',
        "public": true,
        value: 'name',
        "default": 'Spin Module'
      }, {
        name: 'code',
        "public": true,
        value: 'code',
        "default": ''
      }, {
        name: 'version',
        "public": true,
        value: 'version',
        "default": '0.1'
      }
    ];

    function SpinFunction(record) {
      this.record = record;
      this.postCreate = __bind(this.postCreate, this);
      return SpinFunction.__super__.constructor.apply(this, arguments);
    }

    SpinFunction.prototype.postCreate = function(q) {
      return q.resolve(this);
    };

    return SpinFunction;

  })(SuperModel);

  module.exports = SpinFunction;

}).call(this);

//# sourceMappingURL=SpinFunction.js.map
