// Generated by CoffeeScript 1.9.3
(function() {
  var SpinMeta, SuperModel, all, defer,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  SuperModel = require('./SuperModel');

  defer = require('node-promise').defer;

  all = require('node-promise').allOrNone;

  SpinMeta = (function(superClass) {
    extend(SpinMeta, superClass);

    SpinMeta.type = 'SpinMeta';

    SpinMeta.model = [
      {
        name: 'knownModels',
        "public": true,
        value: 'knownModels',
        "default": ['SpinApp', 'SpinModule', 'SpinFunction', 'SpinTag']
      }
    ];

    function SpinMeta(record) {
      this.record = record != null ? record : {};
      this.postCreate = bind(this.postCreate, this);
      return SpinMeta.__super__.constructor.apply(this, arguments);
    }

    SpinMeta.prototype.postCreate = function(q) {
      return q.resolve(this);
    };

    return SpinMeta;

  })(SuperModel);

  module.exports = SpinMeta;

}).call(this);

//# sourceMappingURL=SpinMeta.js.map
