// Generated by CoffeeScript 1.8.0
(function() {
  var DB, OMgr, ResolveModule, SuperModel, all, debug, defer, dirname, error, resolver, uuid,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  defer = require('node-promise').defer;

  all = require('node-promise').allOrNone;

  uuid = require('node-uuid');

  OMgr = require('./OStore');

  DB = require('./DB');

  error = require('./Error').error;

  ResolveModule = require('./ResolveModule');

  console.log('supermodel dirname is ' + __dirname);

  console.log(__dirname);

  dirname = __dirname.substring(0, __dirname.indexOf('/node_modules'));

  if (__dirname.indexOf('node_modules') === -1) {
    dirname = '../..';
  }

  console.log('starting module resolving from path ' + dirname);

  resolver = new ResolveModule(dirname);

  debug = process.env["DEBUG"];

  SuperModel = (function() {
    SuperModel.resolver = resolver;

    SuperModel.prototype._getRecord = function() {
      var rv;
      rv = this.getRecord();
      rv._rev = this._rev;
      return rv;
    };

    function SuperModel(record) {
      var q;
      this.record = record != null ? record : {};
      this.insertObj = __bind(this.insertObj, this);
      this.loadFromIds = __bind(this.loadFromIds, this);
      this.serialize = __bind(this.serialize, this);
      this.toClient = __bind(this.toClient, this);
      this.getRecord = __bind(this.getRecord, this);
      this._getRecord = __bind(this._getRecord, this);
      q = defer();
      this.id = this.record.id || uuid.v4();
      OMgr.storeObject(this);
      if (this.record._rev) {
        if (debug) {
          console.log('setting _rev to ' + this.record._rev + ' for ' + this.type + ' ' + this.id);
        }
        this._rev = this.record._rev;
      }
      this.loadFromIds(this.resolvearr).then((function(_this) {
        return function(a) {
          if (_this.postCreate) {
            return _this.postCreate(q);
          } else {
            return q.resolve(_this);
          }
        };
      })(this), error);
      return q;
    }

    SuperModel.prototype.getRecord = function() {
      return this._getRecord(this, this.resolvearr, this.record);
    };

    SuperModel.prototype._getRecord = function(me, resolvearr, record) {
      var rv;
      rv = {};
      resolvearr.forEach(function(v) {
        var hk, hv, k, varr, _ref;
        k = v.name;
        if (v.value) {
          return rv[k] = v.value || record[k];
        } else if (v.hashtable) {
          varr = [];
          _ref = me[v.name];
          for (hk in _ref) {
            hv = _ref[hk];
            varr.push(hv.id);
          }
          return rv[k] = varr;
        } else if (v.array) {
          varr = [];
          me[v.name].forEach(function(hv) {
            return varr.push(hv.id);
          });
          return rv[k] = varr;
        } else {
          return rv[k] = me[k].id;
        }
      });
      return rv;
    };

    SuperModel.prototype.toClient = function() {
      var k, r, ra, rv, v;
      r = this.getRecord();
      ra = this.resolvearr;
      rv = {};
      for (k in r) {
        v = r[k];
        ra.forEach(function(el) {
          if (el.name === k && el["public"]) {
            return rv[k] = v;
          }
        });
      }
      return rv;
    };

    SuperModel.prototype.serialize = function() {
      var q, record;
      q = defer();
      if (!this._serializing) {
        this._serializing = true;
        record = this._getRecord();
        if (this._rev) {
          record._rev = this._rev;
        }
        OMgr.storeObject(this);
        DB.set(this.type, record).then((function(_this) {
          return function() {
            _this._serializing = false;
            return q.resolve(_this);
          };
        })(this));
      } else {
        q.resolve(this);
      }
      return q;
    };

    SuperModel.prototype.loadFromIds = function(resolvearr) {
      var alldone, allpromises, q;
      if (debug) {
        console.log('------------------------------------------------> loadfromIds called for ' + this.type + ' ' + this.id + ' ' + resolvearr.length + ' properties');
      }
      if (debug) {
        console.dir(resolvearr);
      }
      alldone = defer();
      allpromises = [];
      if (!resolvearr || resolvearr.length === 0) {
        console.log(' ++++++++++++++++ NO RESOLVEARR ++++++++++++++');
        q = defer();
        allpromises.push(q);
        q.resolve();
      } else {
        resolvearr.forEach((function(_this) {
          return function(robj) {
            return (function(resolveobj) {
              var count, r;
              r = defer();
              allpromises.push(r);
              if (resolveobj.value) {
                _this[resolveobj.name] = resolveobj.value;
              }
              if (resolveobj.array === true) {
                _this[resolveobj.name] = [];
              }
              if (resolveobj.hashtable === true) {
                _this[resolveobj.name] = {};
              }
              if (!resolveobj.ids || typeof resolveobj.ids === 'undefined' || resolveobj.ids === 'undefined') {
                resolveobj.ids = [];
                if (debug) {
                  console.log('============================== null resolveobj.ids for ' + resolveobj.type + ' [' + resolveobj.name + ']');
                }
                return r.resolve(null);
              } else {
                if (typeof resolveobj.ids === 'string') {
                  resolveobj.ids = [resolveobj.ids];
                }
                if (debug) {
                  console.log('resolveobjds ' + resolveobj.name + ' (' + (typeof resolveobj.ids) + ') ids length are.. ' + resolveobj.ids.length);
                }
                count = resolveobj.ids.length;
                if (count === 0) {
                  if (debug) {
                    console.log('no ids for ' + resolveobj.name + ' so resolving null');
                  }
                  return r.resolve(null);
                } else {
                  return resolveobj.ids.forEach(function(id) {
                    if (debug) {
                      console.log('trying to get ' + resolveobj.name + ' with id ' + id);
                    }
                    return OMgr.getObject(id, resolveobj.type).then(function(oo) {
                      if (oo) {
                        if (debug) {
                          console.log('found existing instance of ' + resolveobj.name + ' type ' + resolveobj.type + ' in OStore');
                        }
                        _this.insertObj(resolveobj, oo);
                        if (--count === 0) {
                          if (debug) {
                            console.log('resolving ' + resolveobj.name + ' type ' + resolveobj.type + ' immediately');
                          }
                          return r.resolve(oo);
                        }
                      } else {
                        if (debug) {
                          console.log('did not find obj ' + resolveobj.name + ' of type ' + resolveobj.type + ' in OStore. Getting from DB...');
                        }
                        return DB.get(resolveobj.type, [id]).then(function(record) {
                          return resolver.createObjectFrom(record).then(function(obj) {
                            if (debug) {
                              console.log('object ' + resolveobj.name + ' type ' + resolveobj.type + ' created: ' + obj.id);
                            }
                            _this.insertObj(resolveobj, obj);
                            if (--count === 0) {
                              return r.resolve(obj);
                            }
                          }, error);
                        }, error);
                      }
                    }, error);
                  });
                }
              }
            })(robj);
          };
        })(this));
      }
      all(allpromises, error).then((function(_this) {
        return function(results) {
          if (debug) {
            console.log('<------------------------------------------------ loadfromIds done for ' + _this.type + ' ' + _this.id + ' ' + resolvearr.length + ' properties');
          }
          return alldone.resolve(results);
        };
      })(this), error);
      return alldone;
    };

    SuperModel.prototype.insertObj = function(ro, o) {
      if (ro.array === true) {
        if (debug) {
          console.log('inserting obj ' + ro.type + ' as array');
        }
        this[ro.name].push(o);
      } else if (ro.hashtable === true) {
        if (debug) {
          console.log('inserting obj ' + ro.type + ' as hashtable');
        }
        this[ro.name][o.name] = o;
      } else {
        if (debug) {
          console.log('inserting obj ' + ro.type + ' as scalar');
        }
        this[ro.name] = o;
      }
      return OMgr.storeObject(o);
    };

    return SuperModel;

  })();

  module.exports = SuperModel;

}).call(this);

//# sourceMappingURL=SuperModel.js.map
