// Generated by CoffeeScript 1.8.0
(function() {
  var ClientEndpoints, IO, WsMethod, uuid,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  IO = require("socket.io");

  uuid = require('node-uuid');

  ClientEndpoints = require('./ClientEndpoints');

  WsMethod = (function() {
    WsMethod.wsroutes = [];

    function WsMethod(messageRouter, server) {
      var io;
      this.messageRouter = messageRouter;
      this.expose = __bind(this.expose, this);
      io = IO(server);
      io.set('origins', '*:*');
      io.on("connection", function(socket) {
        var adr, ip, port;
        ip = socket.request.connection.remoteAddress;
        port = socket.request.connection.remotePort;
        adr = ip + ':' + port;
        console.log('new ws connection from ' + adr);
        ClientEndpoints.registerEndpoint(adr, function(msg) {
          return socket.emit('message', msg);
        });
        socket.on("message", function(datastring) {
          var data, fn;
          console.log('got new message "' + datastring + '" [' + (typeof datastring) + ']');
          if (typeof datastring === "string") {
            data = JSON.parse(datastring);
          } else {
            data = datastring;
          }
          data.client = ip + ':' + port;
          data.messageId = data.messageId || uuid.v4();
          data.replyFunc = function(replydata) {
            replydata.messageId = data.messageId;
            return socket.emit('message', replydata);
          };
          fn = WsMethod.wsroutes[data.target];
          return typeof fn === "function" ? fn(data) : void 0;
        });
        return socket.on("disconnect", function() {
          adr = ip + ':' + port;
          console.log('client at ' + adr + ' disconnected');
          return ClientEndpoints.removeEndpoint(adr);
        });
      });
      this.messageRouter.addMethod('ws', this);
    }

    WsMethod.prototype.registrationFunc = function(targetName, targetFunc) {
      return WsMethod.wsroutes[targetName] = targetFunc;
    };

    WsMethod.prototype.expose = function(type) {
      this.messageRouter.addTarget('_create' + type, 'obj', (function(_this) {
        return function(msg) {
          msg.type = type;
          return _this.messageRouter.objectManager._createObject(msg);
        };
      })(this));
      this.messageRouter.addTarget('_delete' + type, 'obj', (function(_this) {
        return function(msg) {
          msg.type = type;
          return _this.messageRouter.objectManager._deleteObject(type);
        };
      })(this));
      this.messageRouter.addTarget('_update' + type, 'obj', (function(_this) {
        return function(msg) {
          msg.type = type;
          return _this.messageRouter.objectManager._updateObject(type);
        };
      })(this));
      this.messageRouter.addTarget('_get' + type, 'obj', (function(_this) {
        return function(msg) {
          msg.type = type;
          return _this.messageRouter.objectManager._getObject(type);
        };
      })(this));
      return this.messageRouter.addTarget('_list' + type + 's', '<noargs>', (function(_this) {
        return function(msg) {
          msg.type = type;
          console.log('calling _listObjects from WsMethod with type ' + type);
          return _this.messageRouter.objectManager._listObjects(type);
        };
      })(this));
    };

    return WsMethod;

  })();

  module.exports = WsMethod;

}).call(this);

//# sourceMappingURL=WsMethod.js.map
