// Generated by CoffeeScript 1.8.0
(function() {
  define(['ractive'], (function(_this) {
    return function(Ractive) {
      var listelement;
      listelement = Ractive.extend({
        isolated: false,
        template: '<div>Bar</div>'
      });
      console.log('listelement defined');
      return listelement;
    };
  })(this));

}).call(this);

//# sourceMappingURL=listelement.js.map
