// Generated by CoffeeScript 1.8.0
(function() {
  define(['ractive'], (function(_this) {
    return function(Ractive) {
      var mdldialog;
      mdldialog = Ractive.extend({
        components: {},
        isolated: false,
        data: function() {
          return {
            type: '',
            guid: '',
            currentDialogCallback: '',
            onSelectedItem: (function(_this) {
              return function(e) {
                var cb, dialog;
                console.log('mdldialog selected callback');
                cb = _this.get('currentDialogCallback');
                if (cb) {
                  cb(e.context);
                }
                dialog = _this.find('#' + _this.get('guid') + '-dialog');
                return dialog.close();
              };
            })(this)
          };
        },
        oninit: function() {
          var guid;
          guid = this._guid;
          this.set('guid', guid);
          return window.subscribe('modeldialogopen', (function(_this) {
            return function(args) {
              var cb, dialog;
              cb = args.cb;
              _this.set('type', args.type);
              console.log('--on dialog open');
              _this.set('currentDialogCallback', cb);
              dialog = document.getElementById(guid + '-dialog');
              console.log('guid is ' + guid);
              console.dir(_this.el);
              return dialog.showModal();
            };
          })(this));
        },
        oncomplete: function() {},
        onClose: function() {
          var dialog;
          dialog = this.find('#' + this.get('guid') + '-dialog');
          return dialog.close();
        },
        template: "<dialog class=\"mdl-dialog\" id='{{guid}}-dialog'>\n  <h4 class=\"mdl-dialog__title\">Select {{type}}</h4>\n  <div class=\"mdl-dialog__content\">\n    <p>\n    {{#type}}\n      <modelspinlist type='{{type}}' onSelected='{{onSelectedItem}}'></modelspinlist>\n    {{/}}\n    </p>\n  </div>\n  <div class=\"mdl-dialog__actions\">\n    <button type=\"button\" class=\"mdl-button\" on-click='onClose()'>Close</button>\n  </div>\n</dialog>"
      });
      console.log('mdldialog defined');
      return mdldialog;
    };
  })(this));

}).call(this);

//# sourceMappingURL=mdldialog.js.map
