// Generated by CoffeeScript 1.10.0
(function() {
  define(['ractive'], (function(_this) {
    return function(Ractive) {
      var spinmodel;
      spinmodel = Ractive.extend({
        isolated: false,
        data: function() {
          return {
            model: '',
            getPropertyFor: (function(_this) {
              return function(prop) {
                return _this.get('model')[prop];
              };
            })(this)
          };
        },
        template: '<div> {{#model:prop}} <div> array = {{prop.array}} {{#!prop.array}} {{prop}} - {{getPropertyFor(prop)}} {{/}} {{#prop.array}} <button on-click="onSelectModel()" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"> Select {{type}} </button> <spinlist list="{{getPropertyFor(prop)}}" header="{{prop.type}}" onSelected="{{onSelected}}" onDeleted="{{onDeleted}}"></spinlist> {{/}} </div> {{/model}} </div>'
      });
      console.log('spinmodel defined');
      return spinmodel;
    };
  })(this));

}).call(this);

//# sourceMappingURL=spinmodel.js.map
