// Generated by CoffeeScript 1.10.0
(function() {
  define(['ractive'], (function(_this) {
    return function(Ractive) {
      var spinlist;
      spinlist = Ractive.extend({
        components: {},
        isolated: false,
        data: function() {
          return {
            list: [],
            header: 'List',
            labels: 'name',
            onSelected: '',
            onDeleted: '',
            getLabelFor: function(i) {
              var el, rv;
              el = this.get('list.' + i);
              rv = '';
              if (el) {
                this.get('labels').split(',').forEach(function(label) {
                  return rv += el[label];
                });
              }
              return rv;
            }
          };
        },
        oninit: function() {
          console.log('spinlist created');
          console.dir(this.get('list'));
          this.on('itemSelected', (function(_this) {
            return function(e) {
              var selected;
              console.log('onselected');
              selected = _this.get('onSelected');
              console.dir(selected);
              if (selected) {
                return selected(e);
              }
            };
          })(this));
          this.on('deleted', function(e) {
            var deleted;
            console.log('* item delete clicked');
            deleted = this.get('onDeleted');
            if (deleted) {
              return deleted(e);
            }
          });
          return console.log('spinlist done');
        },
        template: "<div style='display:flex; flex-direction: column'>\n  <h4 style='margin-bottom:0'>{{header}}</h4>\n  <ul class=\"mdl-list\" style='margin-top:0'>\n  {{#list:i}}\n    <div style='display:flex; flex-direction: row'>\n      <i on-click=\"deleted\" class=\"mdl-color-text--blue-grey-400 material-icons\" role=\"presentation\">delete</i>\n      <li class=\"mdl-list__item\" style=\"min-height:30px; padding-top:0; padding-bottom:0\" on-click='itemSelected'>{{ getLabelFor(i) }}</li>\n    </div>\n  {{/}}\n  </ul>\n</div>"
      });
      console.log('spinlist defined');
      return spinlist;
    };
  })(this));

}).call(this);

//# sourceMappingURL=spinlist.js.map
