// Generated by CoffeeScript 1.8.0
(function() {
  define(['ractive', 'components/listelement'], (function(_this) {
    return function(Ractive, listelement) {
      var spinlist;
      spinlist = Ractive.extend({
        components: {
          listelement: listelement
        },
        isolated: false,
        data: function() {
          return {
            list: [],
            header: 'List',
            labels: 'name',
            getLabelFor: function(i) {
              var el, rv;
              el = this.get('list.' + i);
              rv = '';
              this.get('labels').split(',').forEach(function(label) {
                return rv += el[label];
              });
              return rv;
            }
          };
        },
        oninit: function() {
          return this.on('itemSelected', function(e) {
            console.log('item selected ');
            return console.dir(e);
          });
        },
        template: "<div style='display:flex; flex-direction: column'>\n  <h4 style='margin-bottom:0'>{{header}}</h4>\n  <ul class=\"mdl-list\" style='margin-top:0'>\n  {{#list:i}}\n    <li class=\"mdl-list__item\" on-click='itemSelected'>{{ getLabelFor(i) }}</li>\n  {{/}}\n  </ul>\n</div>"
      });
      console.log('spinlist defined');
      return spinlist;
    };
  })(this));

}).call(this);

//# sourceMappingURL=spinlist.js.map
