// Generated by CoffeeScript 1.8.0
(function() {
  define(['ractive', 'components/listelement'], (function(_this) {
    return function(Ractive, listelement) {
      var spinlist;
      spinlist = Ractive.extend({
        components: {
          listelement: listelement
        },
        isolated: false,
        data: function() {
          return {
            list: [],
            header: 'List',
            labels: 'name',
            getLabelFor: function(i) {
              var el, rv;
              el = this.get('list.' + i);
              rv = '';
              this.get('labels').split(',').forEach(function(label) {
                return rv += el[label];
              });
              return rv;
            }
          };
        },
        template: "<h4>{{header}}</h4>\n<ul class=\"mdl-list\">\n{{#list:i}}\n  <li class=\"mdl-list__item\">{{ getLabelFor(i) }}</li>\n{{/}}\n</ul>"
      });
      console.log('spinlist defined');
      return spinlist;
    };
  })(this));

}).call(this);

//# sourceMappingURL=spinlist.js.map
